
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmhzyedrospylioszxbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptaHp5ZWRyb3NweWxpb3N6eGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzY3ODYsImV4cCI6MjA1NzYxMjc4Nn0.lLKiVDOFViYVJxBBaiO75nForuyAZfmQ-V2W_jNLSoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
    },
    global: {
      headers: {
        'x-application-name': 'ok-sale',
      },
    },
  }
);
